### ISSUE TITLE
Please enhance the doc

### ISSUE THREAD

**Issue by cilex-ft** [simplesamlphp/simplesamlphp-module-cas#1]
CAS V3 (since 2017) supports querying attributes. Those have to be published for the service you're calling.

To get them, you might have to call serviceValidate for Protocol 3 via **/p3/**:

```
	'cas' => array(
		'serviceValidate' => 'https://cas.example.com/p3/serviceValidate',
```
which would return something like

```
    <cas:authenticationSuccess>
        <cas:user>jdoe</cas:user>
        <cas:attributes>
            <cas:credentialType>UsernamePasswordCredential</cas:credentialType>
            <cas:isFromNewLogin>false</cas:isFromNewLogin>
            <cas:mail>john.doe@example.com</cas:mail>
            <cas:authenticationDate>2021-01-19T08:38:49.624+01:00[Europe/Paris]</cas:authenticationDate>
            <cas:authenticationMethod>LdapAuthenticationHandler</cas:authenticationMethod>
            <cas:firstName>John</cas:firstName>
            <cas:successfulAuthenticationHandlers>LdapAuthenticationHandler</cas:successfulAuthenticationHandlers>
            <cas:longTermAuthenticationRequestTokenUsed>false</cas:longTermAuthenticationRequestTokenUsed>
            <cas:sn>Doe</cas:sn>
            </cas:attributes>
    </cas:authenticationSuccess>
```

So we can query for attributes in authsources.php:

```
	'cas' => array(
		'attributes' => [
		    'uid' => '/cas:serviceResponse/cas:authenticationSuccess/cas:user',
		    'sn' => '/cas:serviceResponse/cas:authenticationSuccess/cas:attributes/cas:sn',
		    'givenName' => '/cas:serviceResponse/cas:authenticationSuccess/cas:attributes/cas:firstname',
		    'mail' => '/cas:serviceResponse/cas:authenticationSuccess/cas:attributes/cas:mail',
		    ],
```

and even some custom attributes if they're set:

		    'customabc' => '/cas:serviceResponse/cas:authenticationSuccess/custom:abc',

Also, one can set ldap to a null array to avoid connecting to LDAP to query for attributes (but `ldap` MUST be set):

```
'example-cas' => array(
	'cas:CAS',
	'cas' => array(
            ...
	),
	'ldap' => []
```

Maybe the doc / example should be updated... we spent hours figuring this out.

**Comment by thijskh** [comment]
Excellent suggestion to update the docs with this. Would you be able to create a pull request for that?

**Comment by cilex-ft** [comment]
Sorry I'm afraid I don't know how to submit those, I'm not a pro programmer...

**Comment by thijskh** [comment]
It’s actually not so hard, go to the docs file and edit it online: https://github.com/simplesamlphp/simplesamlphp-module-cas/edit/master/docs/cas.md

You can preview your changes and create a PR without the need to program.

**Comment by cilex-ft** [comment]
Ok @thijskh github created a fork for me, where I entered my edits, then I created a PR. I'll watch this space in case I botched something...

**Comment by tvdijen** [comment]
Thanks @cilex-ft, for the docs! I've merged your contribution.
